archives/urls.py
from django.conf.urls.defaults import *
from django.conf.urls import patterns, include, url
from django.conf import settings
import os
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
                       url(r'^$', 'archives.general.home', name='home'),
                       url(r'^login/$', 'archives.general.signin'),
                       url(r'^logout/$', 'archives.general.signout'),
                       url(r'^upload/$', 'archives.upload.home', name='upload'),
                       url(r'^archive/$', 'archives.archive.home'),
                       url(r'^archive/author/$', 'archives.archive.authors'),
                       url(r'^archive/author/(?P<author_id>\w+)/$', 'archives.archive.author'),
                       url(r'^archive/year/$', 'archives.archive.years'),
                       url(r'^archive/year/(?P<year>\d+)/$', 'archives.archive.year'),
                       url(r'^photo/$', 'archives.photo.home'),
                       url(r'^photo/(?P<photo_uuid>\w{32})/$', 'archives.photo.detail'),
                       url(r'^photo/(?P<photo_uuid>\w{32})/delete/$', 'archives.photo.delete'),
                       url(r'^photo/(?P<photo_uuid>\w{32})/update/$', 'archives.photo.update'),
                       url(r'^photo/(?P<photo_uuid>\w{32})/rotate/$', 'archives.photo.rotate'),
                       url(r'^author/$', 'archives.author.home'),
                       url(r'^author/meibo/$', 'archives.author.meibo'),
                       url(r'^author/meibo/add/$', 'archives.author.meiboadd'),
                       url(r'^author/(?P<author_id>\w+)/$', 'archives.author.detail'),
                       url(r'^author/(?P<author_id>\w+)/update/$', 'archives.author.update'),
                       url(r'^group/$', 'archives.group.home'),
                       url(r'^group/(?P<group_id>\d+)/$', 'archives.group.detail'),
                       url(r'^group/(?P<group_id>\d+)/update/$', 'archives.group.update'),
                       url(r'^group/(?P<group_id>\d+)/delete/$', 'archives.group.delete'),
                       url(r'^group/meibo/add/$', 'archives.group.meiboadd'),
                       url(r'^tag/$', 'archives.tag.home'),
                       url(r'^tag/(?P<tag_id>\d+)/$', 'archives.tag.detail'),
                       url(r'^tag/(?P<tag_id>\d+)/update/$', 'archives.tag.update'),
                       url(r'^tag/(?P<tag_id>\d+)/delete/$', 'archives.tag.delete'),
                       url(r'^tag/meibo/add/$', 'archives.tag.meiboadd'),
                       url(r'^search/$', 'archives.search.home'),
                       url(r'^search/author/$', 'archives.search.author'),
                       url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
                       url(r'^adminsite/', include(admin.site.urls)),
                       )

iArchives/urls.py
from django.conf.urls.defaults import *
from django.conf.urls import patterns, include, url
from django.conf import settings
import os


urlpatterns = patterns('',
                       # (r'^admin/(.*)', admin.site.root),
                       # url(r'^$', 'archives.general.home', name='home'),
                       url(r'^(/)?', include('archives.urls')),
                       url(r'^404/$', 'iArchives.views.status404', name='404'),
                       )

# urlpatterns = patterns('',
#                        # url(r'^$', 'iArchives.views.home', name='home'),
#                        # include app urls.py file
#                        url(r'^(/)?', include('iArchives.iarchives.urls')),
# )
if settings.DEBUG:
    urlpatterns += patterns('',
                            (r'^static/(?P<path>.*)$','django.views.static.serve',
                             {'document_root': settings.STATIC_ROOT}),
                            (r'^media/(?P<path>.*)$','django.views.static.serve',
                             {'document_root': settings.MEDIA_ROOT}),
                            (r'^admin/(?P<path>.*)$','django.views.static.serve',
                             {'document_root': settings.ADMIN_MEDIA_PREFIX}),

                            )

archives/models.py
#!/usr/bin/env python
# encoding: utf-8
"""
models.py

Created by mmiyaji on 2012-07-16.
Copyright (c) 2012  ruhenheim.org. All rights reserved.
"""

import sys, os, datetime, uuid
from django.db import models
from django.db.models import Q
from django.core.cache import cache
from django.conf import settings
from django.utils.encoding import force_unicode, smart_str
from PIL import Image
from cStringIO import StringIO
from django.core.files.uploadedfile import SimpleUploadedFile

class Author(models.Model):
    """
    著者モデル
    QRコードから抽出した情報を保持する
    """
    name = models.CharField(max_length = 100, default="", blank=True, null=True, db_index=True)
    nickname = models.CharField(max_length=255, blank=True, null=True)
    roman = models.CharField(max_length=255, blank=True, null=True)
    student_id = models.CharField(max_length = 100, default="", blank=True, null=True, unique=True, db_index=True)
    ROLL_CHOICES = (
        ('s','Student'),
        ('t','Teacher'),
        ('g','Graduated'),
        ('e','Etcetera'),
        )
    roll = models.CharField(max_length=10, choices=ROLL_CHOICES, default="s", db_index=True)
    isvalid = models.BooleanField(default=True, db_index=True)
    admitted_at = models.DateTimeField(blank=True, null=True, db_index=True)
    graduated_at = models.DateTimeField(blank=True, null=True, db_index=True)
    updated_at = models.DateTimeField(auto_now = True, db_index=True)
    created_at = models.DateTimeField(auto_now_add = True, db_index=True)
    def get_photos(self, span=10, page=0, search_query=None, isvalid=True, order="-created_at", all=False, listvalue=None):
        """
        自分の著作を返す
        """
        result,count = Photo.get_items(author=self, span=span, page=page, search_query=search_query, isvalid=isvalid, order=order, all=all, listvalue=listvalue)
        return result,count
    def get_photo_num(self):
        """
        自分の著作の数を返す
        """
        num = Photo.objects.filter(authors__exact=self).count()
        return num
    def get_groups(self):
        """
        自分の所属グループリスト（年度別）を返す
        """
        result = GroupHandler.get_by_author(self)
        return result
    def my_groups(self):
        # 所属するグループのリストを作成
        groups = []
        try:
            g = self.get_groups()
            syear = self.admitted_at.year
            for i in range(syear, syear+6):
                gh = GroupHandler.get_item(self,i)
                gn = ""
                if gh and gh.group: gn = gh.group.name
                groups.append((i,gn))
        except:
            pass
        return groups
    @staticmethod
    def get_years():
        """
        すべての入学年度のリストを返す
        """
        return Author.objects.dates('admitted_at', 'year')
    @staticmethod
    def get_items(span=10, page=0, search_query=None, admitted_query=None, query_type=False,
                  group_year=None, group_name=None,
                  isvalid=True, order="-created_at", all=False, listvalue=None):
        result = None
        result_count = 0
        if page!=0:
            page = page*span - span
        endpage = page + span
        try:
        # if True:
            # 検索対象のすべてのエントリー数とSPANで区切ったエントリーを返す
            result = Author.objects.order_by(order).filter(isvalid=isvalid)
            if admitted_query:
                result = result.filter(admitted_at__year=admitted_query)
            if group_name:
                group = Group.get_by_name(group_name)
                if group_year:
                    result = result.filter(grouphandler__group=group,grouphandler__year__year=group_year) # 後方参照
                else:
                    result = result.filter(grouphandler__group=group) # 後方参照
            else:
                if group_year:
                    result = result.filter(grouphandler__year__year=group_year) # 後方参照
            if search_query:
                # 漢字とよみがなの場合を結合して検索．ANDかつ混合時には検索対象にならない
                qs1 = [Q(name__icontains=w) for w in search_query]
                qs2 = [Q(roman__icontains=w) for w in search_query]
                query1 = qs1.pop()
                query2 = qs2.pop()
                if query_type: # AND method
                    for q in qs1:
                        query1 &= q
                    for q in qs2:
                        query2 &= q
                else: # OR method
                    for q in qs1:
                        query1 |= q
                    for q in qs2:
                        query2 |= q
                query = query1 | query2
                result = result.filter(query)
            result_count = result.count()
            if not all:
                result = result[page:endpage]
            if listvalue:
                result = result.values_list(listvalue)
        except:
            pass
        return result, result_count
    @staticmethod
    def get_by_student_id(keyid=""):
        result=None
        try:
            result = Author.objects.get(student_id__exact=keyid.strip())
        except:
            result = None
        return result

    def __str__(self):
        return "%s" % (self.name)
    def __unicode__(self):
        return self.name

def get_origin_photo_upload_path(self, filename):
    return get_photo_upload_path(self, filename, types="originals")
def get_thumb_photo_upload_path(self, filename):
    return get_photo_upload_path(self, filename, types="thumbs")
def get_photo_upload_path(self, filename, types="originals"):
    root_path = "archives/"+types+"/%Y/%m/%d/"
    now = self.published_at
    # user_path =  os.path.join(settings.MEDIA_ROOT, force_unicode(now.strftime(smart_str(root_path))))
    user_path = force_unicode(now.strftime(smart_str(root_path)))
    # name = force_unicode(now.strftime((smart_str("%Y%m%d%H%M%S_"+str(self.id).zfill(5)+"."+filename.split(".")[-1]))))
    if types == "originals":
        # at the case of originals, set title
        name = self.title
        # self.title = name
    else:
        name = os.path.splitext(os.path.basename(self.title))[0]+"."+filename.split(".")[-1]
    return os.path.join(user_path, name)
class Tag(models.Model):
    """
    タグモデル
    写真につけるタグの定義
    """
    name = models.CharField(max_length = 100, default="", blank=True, null=True)
    roman = models.CharField(max_length = 100, default="", blank=True, null=True)
    image_url = models.CharField(max_length = 255, default="", blank=True, null=True)
    comment = models.TextField(default="", db_index=True)
    isvalid = models.BooleanField(default=True, db_index=True)
    updated_at = models.DateTimeField(auto_now = True, db_index=True)
    created_at = models.DateTimeField(auto_now_add = True, db_index=True)
    @staticmethod
    def get_all():
        return Tag.objects.filter(isvalid__exact=True)
    @staticmethod
    def get_items(page=0, span=10):
        result = Tag.objects.filter(isvalid__exact=True)
        if page!=0:
            page = page*span - span
            endpage = page + span
        return result[page:endpage],result.count()
    @staticmethod
    def tag_list():
        return Tag.objects.all()
    @staticmethod
    def get_by_id(id):
        result=None
        try:
            result = Tag.objects.get(id=int(id))
        except:
            result = None
        return result
    @staticmethod
    def get_by_name(name=""):
        result=None
        try:
            result = Tag.objects.filter(name=name).get()
        except:
            result = None
        return result
    def __unicode__(self):
        return self.name
    def get_absolute_url(self):
        return "/tag/%s" % self.id

class Photo(models.Model):
    """
    写真モデル
    アップロードした写真を保存、保存時にQRコードとExif情報を解析してメタ情報を記録しておく
    保存時には、自動で縮小したサムネイル用画像も作成する
    """
    authors = models.ManyToManyField(Author, blank=True, null=True, db_index=True)
    uuid = models.CharField(max_length = 32, default="", db_index=True)
    title = models.CharField(max_length = 100, default="", blank=True, null=True)
    original_title = models.CharField(max_length = 100, default="", blank=True, null=True)
    orientation = models.IntegerField(default=0, blank=True, null=True)
    image = models.ImageField(upload_to=get_origin_photo_upload_path,
                              width_field="image_width",
                              height_field="image_height",
                              blank=True, null=True
                              )
    image_width = models.IntegerField(blank=True, null=True)
    image_height = models.IntegerField(blank=True, null=True)
    thumbnail = models.ImageField(upload_to=get_thumb_photo_upload_path,
                                  width_field="thumbnail_width",
                                  height_field="thumbnail_height",
                                  blank=True, null=True
                                  )
    thumbnail_width = models.IntegerField(blank=True, null=True)
    thumbnail_height = models.IntegerField(blank=True, null=True)
    caption = models.CharField(max_length = 250, default="", blank=True, null=True, db_index=True)
    comment = models.TextField(default="", db_index=True)
    isvalid = models.BooleanField(default=True, db_index=True)
    published_at = models.DateTimeField(blank=True, null=True, db_index=True)
    updated_at = models.DateTimeField(auto_now = True, db_index=True)
    created_at = models.DateTimeField(auto_now_add = True, db_index=True)
    tag = models.ManyToManyField(Tag, blank=True, null=True, db_index=True)
    @staticmethod
    def get_years():
        """
        すべての登録書籍の年度リストを返す
        """
        return Photo.objects.dates('published_at', 'year')
    @staticmethod
    def get_items(author=None, span=10, page=0,
                  search_query=None, admitted_query=None, published_query=None, tag_queries=None, query_type=False,
                  order="-published_at", search_target=0, isvalid=True, all=False, listvalue=None):
        result = None
        result_count = 0
        if page!=0:

archives/views.py
#!/usr/bin/env python
# encoding: utf-8
"""
views.py

Created by mmiyaji on 2012-07-11.
Copyright (c) 2012  ruhenheim.org. All rights reserved.
"""

import os, re, sys, commands, time, datetime, random, logging
from django.http import HttpResponse, HttpResponseRedirect
from django.template import Context, loader
from django.template import RequestContext
from django.shortcuts import render_to_response
from django.core.urlresolvers import reverse
from django.contrib import auth
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_protect
from archives.models import *
from django.utils.encoding import force_unicode, smart_str
from django.core import serializers
from django.conf import settings
from django.http import Http404

# from utils import *
# from getimageinfo import *
# import isbooks.networkx as nx
# from django.core.cache import cache
logger = logging.getLogger('app')
def date_validate(date, dateformat="%Y-%m-%d"):
    # 指定したフォーマットでdatetimeオブジェクトに変換可能かチェック
    try:
        return datetime.datetime.strptime(date, dateformat)
    except:
        return None
def replace_validname(filename):
    valid = ["/", "*", "?", "\\", ";", ":" ]
    exp = "_"
    for i in valid:
        filename = filename.replace(i, exp)
    return filename
def get_page_list(page, count, search_span, view_max=13):
    # pagerのために必要な値を計算するメソッド
    pages = dict()
    page_max = (count / search_span)
    if page <= 0:
        page = 1
    if count%search_span!=0:
        page_max +=1
        pre_page = None
    next_page = None
    if page_max >= page+1:
        next_page = page+1
    if page!=0:
        pre_page = page-1
    pages['next_page'] = next_page
    pages['now_page'] = page
    pages['pre_page'] = pre_page
    pages['max'] = count
    pages['start'] = (page-1)*search_span+1
    end = 0
    if (page)*search_span>=count:
        end=count
    else:
        end = (page)*search_span
    pages['end'] = end
    page_list = []
    if page_max>(view_max+2):
        page_list.append(1)
        mins = page-(int)(view_max/2)
        maxs = page+(int)(view_max/2)
        if (maxs - mins) < view_max:
            mins = maxs - view_max
        if mins<2:
            mins = 2
            maxs = view_max
        else:
            page_list.append(-1)
        if maxs>page_max:
            maxs = page_max
        for x in range(mins, maxs):
            page_list.append(x)
        if maxs<page_max:
            page_list.append(-1)
        page_list.append(page_max)
    else:
        for x in range(1, page_max+1):
            page_list.append(x)
        if len(page_list)==1:
            page_list = None
    return page_list,pages
def main():
    pass


if __name__ == '__main__':
    main()

archives/templates/archive/authors.html
{% extends "base/base.html" %}
{% block main %}
<!-- Masthead
     ================================================== -->
<header class="jumbotron subhead" id="overview">
  <h2 id="title">一括書き出し [著者一覧]</h2>
  <p class="lead">{% if pages.max %}全 {{pages.max}}件中 {{pages.start}}~{{pages.end}}件目を表示 / {{pages.now_page}}ページ目{% endif %}</p>
</header>
<!-- Photo view
     ================================================== -->
<div class="btn-toolbar">
  <!-- <div class="btn-group"> -->
  <!--   <button class="btn">ソート順序(学籍番号)</button> -->
  <!--   <button class="btn dropdown-toggle" data-toggle="dropdown"> -->
  <!--     <span class="caret"></span> -->
  <!--   </button> -->
  <!--   <ul class="dropdown-menu"> -->
  <!--     <\!-- dropdown menu links -\-> -->
  <!--     <li><a href="#">ソート順序(学籍番号)</a></li> -->
  <!--     <li><a href="#">ソート順序(氏名)</a></li> -->
  <!--     <li><a href="#">ソート順序(更新日)</a></li> -->
  <!--   </ul> -->
  <!-- </div> -->
  <!-- <div class="btn-group"> -->
  <!--   <button class="btn">昇順</button> -->
  <!--   <button class="btn dropdown-toggle" data-toggle="dropdown"> -->
  <!--     <span class="caret"></span> -->
  <!--   </button> -->
  <!--   <ul class="dropdown-menu"> -->
  <!--     <\!-- dropdown menu links -\-> -->
  <!--     <li><a href="#">昇順</a></li> -->
  <!--     <li><a href="#">降順</a></li> -->
  <!--   </ul> -->
  <!-- </div> -->
  <form class="form-search form-inline input-prepend" action="/archive/author/" method="GET" accept-charset="UTF-8">
    <span class="add-on">入学年度</span>
    <select class="input-medium" name="a">
      <option value="0">すべて</option>
      {% for y in auth_years %}
      <option value="{{y.year}}"{% ifequal y.year admitted_query %}selected{% endifequal %}>{{y.year}} 年度</option>
      {% endfor %}
    </select>
    <span class="add-on">氏名</span>
    <input type="text" class="input-medium" name="q">
    <button type="submit" class="btn">検索</button>
  </form>
  <div class="pagination">
    <ul>
      <p>{% if pages.max %}全 {{pages.max}}件中 {{pages.start}}~{{pages.end}}件目を表示{% endif %}</p>
      {% if pages.pre_page %}
      <li><a href="/archive/author/?page={{pages.pre_page}}">&laquo;</a></li>
      {% endif %}
      {% for page in page_list %}{% ifequal page pages.now_page %}
      <li class="active">
        <a href="#">{{page}}</a>
      </li>{% else %}
      {% ifequal page -1 %}
      <li class="disabled"><a href="#">...</a></li>
      {% else %}
      <li><a href="/archive/author/?page={{page}}">{{page}}</a></li>
      {% endifequal %}{% endifequal %}{% endfor %}
      {% if pages.next_page %}
      <li><a href="/archive/author/?page={{pages.next_page}}">&raquo;</a></li>
      {% endif %}
    </ul>
  </div>
</div>
<section>
  {% if search_query %}
  <div class="page-header">
    <h1>{% if admitted_query %}{{admitted_query}} 年度生 {% endif %}{% if search_query %}[ {% for s in search_query %}{{s}} {% endfor %} ]{% endif %}検索結果</h1>
  </div>
  {% endif %}
  <form id="fileuploads" action="/archive/author/" method="POST" enctype="multipart/form-data" accept-charset="UTF-8">
    <div>
      <table id="author_tables" class="table table-bordered table-striped">
        <thead>
          <tr>
            <th>#</th>
            <th>学籍番号</th>
            <th>入学年度</th>
            <th>氏名</th>
            <th>種別</th>
            {# <th>ニックネーム</th> #}
            {#- <th>氏名読み</th> #}
            <th>最終更新日</th>
            <th>作成日</th>
            <th>登録作品数</th>
            <th>
              <label>
                <i class="icon-check"></i>
                <span>全選択</span>
                <input type="checkbox" id="atoggle" class="atoggle" checked="checked">
              </label>
            </th>
          </tr>
        </thead>
        <tbody>
          {% for author in authors %}
          <tr id="author_{{author.student_id|urlencode}}">
            <td>{{ forloop.counter }}</td>
            <td>{{author.student_id}}</td>
            <td>{{author.admitted_at.year}}</td>
            <td><a href="/author/{{author.student_id}}/" target="_blank">{{author.name}}</a></td>
            <td>{{author.get_roll_display}}</td>
            {# <td>{{author.nickname}}</td> #}
            {# <td>{{author.roman}}</td> #}
            <td>{{author.updated_at}}</td>
            <td>{{author.created_at}}</td>
            <td>{{author.get_photo_num}}</td>
            <td class="command">
              <label>
                <i class="icon-download"></i>
                <span>アーカイブ対象</span>
                <input type="checkbox" class="isarchive" name="isarchive" value="{{author.student_id}}" checked="checked">
              </label>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
    <div class="pagination">
      <p>{% if pages.max %}全 {{pages.max}}件中 {{pages.start}}~{{pages.end}}件目を表示{% endif %}</p>
      <ul>
        {% if pages.pre_page %}
        <li><a href="/author/?page={{pages.pre_page}}">&laquo;</a></li>
        {% endif %}
        {% for page in page_list %}{% ifequal page pages.now_page %}
        <li class="active">
          <a href="#">{{page}}</a>
        </li>{% else %}
        {% ifequal page -1 %}
        <li class="disabled"><a href="#">...</a></li>
        {% else %}
        <li><a href="/author/?page={{page}}">{{page}}</a></li>
        {% endifequal %}{% endifequal %}{% endfor %}
        {% if pages.next_page %}
        <li><a href="/author/?page={{pages.next_page}}">&raquo;</a></li>
        {% endif %}
      </ul>
    </div>
    <hr class="soften">
    <h2 id="select_type">書き出しフォルダ形式設定</h2>
    <div class="row thumbnails">
      <div class="span3">
        <label class="radio">
          <input type="radio" name="archive_type" value="1">
          日付ごとにフォルダ分け(年月日)
          <img class="thumbnail" src="{{ STATIC_URL }}/img/screenshot/ziptype01.png" alt="format y/m/d">
        </label>
      </div>
      <div class="span3">
        <label class="radio">
          <input type="radio" name="archive_type" value="2">
          日付ごとにフォルダ分け(年月)
          <img class="thumbnail" src="{{ STATIC_URL }}/img/screenshot/ziptype02.png" alt="format y/m">
        </label>
      </div>
      <div class="span3">
        <label class="radio">
          <input type="radio" name="archive_type" value="3" checked>
          日付ごとにフォルダ分け(年)
          <img class="thumbnail" src="{{ STATIC_URL }}/img/screenshot/ziptype03.png"  alt="format y">
        </label>
      </div>
      <div class="span3">
        <label class="radio">
          <input type="radio" name="archive_type" value="4">
          すべて同じフォルダ
          <img class="thumbnail" src="{{ STATIC_URL }}/img/screenshot/ziptype04.png" alt="same folder">
        </label>
      </div>
    </div>
    <hr class="soften">
    <h2 id="select_finelame">写真ファイル名設定</h2>
    <div class="row thumbnails">
      <div class="span3">
        <label class="radio">
          <input type="radio" name="archive_filename" value="1">
          自動設定されたファイル名(撮影日)<br>
          例) 20120724192207_00046.jpg
        </label>
      </div>
      <div class="span3">
        <label class="radio">
          <input type="radio" name="archive_filename" value="2">
          オリジナル(元)のファイル名<br>
          例) P1020016.JPG
        </label>
      </div>
      <div class="span3">
        <label class="radio">
          <input type="radio" name="archive_filename" value="3" checked>
          キャプションとして設定した名前(未設定ファイルは日付)<br>
          例) 夏季自由研究.jpg
        </label>
      </div>
    </div>
    <hr class="soften">
    <h2 id="select_zipfile">書き出しファイル名設定</h2>
    <div>
      <div class="controls input-append">
        <label class="control-label">初期設定: archive_日付.zip</label>
        <input type="text" name="archive_zipfile" class="input-xlarge" value="archive_{% now 'YmdHis' %}">
        <span class="add-on">.zip</span>
      </div>
    </div>
    {% csrf_token %}
    <hr class="soften">
    <h2 id="download_archive">ダウンロード</h2>
    <div id="download" class="download-btn">
      <button class="btn btn-success" type="submit">
        <span>アーカイブ化</span>
      </button>
      <div class="alert alert-ja alert-info">
        <p>ファイル数によっては処理に時間がかかる場合があります。ボタンをクリックしたあとはダウンロードダイアログが出てくるまでお待ちください。</p>
      </div>
    </div>
  </form>
</section>
{% endblock main %}